/* ═══════════════════════════════════════════════════════════════════
   SEASONS — ETL-validated data from kiwifruit_export.db
   Generated by 07_api_feed.py | Do not edit manually
   ═══════════════════════════════════════════════════════════════════ */
const SEASONS = {
  '2022/23': {
    dmAvg:         16.79,
    mtsPassRate:   0.899,   // 89.9% pass rate
    totalReturnM:  16.47,  // NZD 16.5M
    pestBase:      25,
    volIndex:      95.0,
    otifAvg:       87.52,
    paymentsReversedM: 2.021,
    climateNote:   'La Niña residual. Moderate season with some wet weather pressure.',
  },
  '2023/24': {
    dmAvg:         17.09,
    mtsPassRate:   0.965,   // 96.5% pass rate
    totalReturnM:  19.31,  // NZD 19.3M
    pestBase:      9,
    volIndex:      102.0,
    otifAvg:       88.32,
    paymentsReversedM: 0.813,
    climateNote:   'El Niño conditions — drier, warmer. Best DM year in dataset.',
  },
  '2024/25': {
    dmAvg:         16.4,
    mtsPassRate:   0.741,   // 74.1% pass rate
    totalReturnM:  13.72,  // NZD 13.7M
    pestBase:      65,
    volIndex:      97.0,
    otifAvg:       85.63,
    paymentsReversedM: 4.897,
    climateNote:   'Cyclone Gabrielle aftermath. High pest pressure. Worst season in dataset.',
  },
  '2025/26': {
    dmAvg:         16.88,
    mtsPassRate:   0.927,   // 92.7% pass rate
    totalReturnM:  18.78,  // NZD 18.8M
    pestBase:      18,
    volIndex:      104.0,
    otifAvg:       87.86,
    paymentsReversedM: 1.635,
    climateNote:   'Recovery season. Strong SunGold pool. Reference year for 2026 analysis.',
  },
};

/* SUBZONES — Dim_Corridor values from ETL pipeline */
const SUBZONES_ETL = {
  'Katikati': {
    dmMean:      16.872,   // ETL: dim_fruit_quality avg
    dmStd:       0.55,
    mtsFailPct:  7.6,
    distanceKm:  52,
    vsi:         1.6,               // Vibration Stress Index
  },
  'Pongakawa': {
    dmMean:      16.802,   // ETL: dim_fruit_quality avg
    dmStd:       0.646,
    mtsFailPct:  8.8,
    distanceKm:  35,
    vsi:         1.5,               // Vibration Stress Index
  },
  'Te Puke': {
    dmMean:      16.721,   // ETL: dim_fruit_quality avg
    dmStd:       0.634,
    mtsFailPct:  11.9,
    distanceKm:  28,
    vsi:         1.4,               // Vibration Stress Index
  },
  'Tauranga': {
    dmMean:      16.663,   // ETL: dim_fruit_quality avg
    dmStd:       0.606,
    mtsFailPct:  11.6,
    distanceKm:  12,
    vsi:         1.0,               // Vibration Stress Index
  },
  'Opotiki': {
    dmMean:      16.369,   // ETL: dim_fruit_quality avg
    dmStd:       0.745,
    mtsFailPct:  26.1,
    distanceKm:  97,
    vsi:         2.5,               // Vibration Stress Index
  },
};
